### PR TITLE
Added offchain proof helpers

### PR DESCRIPTION
**Pull request by fforbeck**
https://github.com/openlawteam/tribute-ui/issues/459

### CODE REVIEW

**Comment by jtrein** [comment]
Hey man, would you also mind migrating the tests for those helpers over as well? Let me know if you have any questions.

**Comment by fforbeck** [comment]
sure @jtrein 
I just added them

**Comment by fforbeck** [comment]
@jtrein would you mind to double check my `msw` config? The tests are passing locally, but on the CI they are failing due to some missing type.

**Comment by jtrein** [comment]
Sure, taking a look

**Review by jtrein — APPROVED** [review]
LGTM!

**Pull request merged**
